"""initial_schema

Revision ID: 43bc71851f0e
Revises: 
Create Date: 2026-09-26 12:32:57.998562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '43bc71851f0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('before_version', sa.BigInteger(), nullable=True),
    sa.Column('after_version', sa.BigInteger(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('safe_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_events_occurred_action', 'audit_events', ['occurred_at', 'action'], unique=False)
    op.create_table('budget_periods',
    sa.Column('scope', sa.Enum('DEVELOPMENT', 'PILOT', name='budget_scope'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('limit_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('reserved_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('spent_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_card_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'period_start', 'period_end', name='uq_budget_period_scope_window')
    )
    op.create_table('jobs',
    sa.Column('type', sa.Enum('INGEST_DOCUMENT', 'EMBED_SANITIZED', 'DRAFT_RUBRIC', 'ASSESS_APPLICATION', 'DRAFT_INTERVIEW', 'PURGE_DATA', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'STALE', name='job_status'), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_epoch', sa.BigInteger(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['priority', 'available_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_target_id'), 'jobs', ['target_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.Enum('SANDBOX', 'PILOT', name='environment_mode'), nullable=False),
    sa.Column('pilot_stage', sa.Enum('SHADOW', 'ASSISTED', name='pilot_stage'), nullable=True),
    sa.Column('stage_gate_report_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('login_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='user_status'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('session_generation', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login_name'), 'users', ['login_name'], unique=True)
    op.create_table('budget_reservations',
    sa.Column('budget_period_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('settled_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_period_id'], ['budget_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_reservations_budget_period_id'), 'budget_reservations', ['budget_period_id'], unique=False)
    op.create_index(op.f('ix_budget_reservations_job_id'), 'budget_reservations', ['job_id'], unique=False)
    op.create_table('candidates',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('public_label', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_organization_id'), 'candidates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_candidates_public_label'), 'candidates', ['public_label'], unique=True)
    op.create_table('deletion_requests',
    sa.Column('scope', sa.Enum('APPLICATION', 'CANDIDATE', name='deletion_scope'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PURGING', 'AWAITING_EXTERNAL', 'COMPLETED', 'FAILED', name='deletion_status'), nullable=False),
    sa.Column('local_purge_complete', sa.Boolean(), nullable=False),
    sa.Column('local_purge_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backup_status', sa.String(length=50), nullable=False),
    sa.Column('backup_expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_retention_status', sa.String(length=50), nullable=False),
    sa.Column('reason_category', sa.String(length=100), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_requests_status'), 'deletion_requests', ['status'], unique=False)
    op.create_index(op.f('ix_deletion_requests_target_id'), 'deletion_requests', ['target_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('route_scope', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('resource_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'method', 'route_scope', 'key', name='uq_idempotency_actor_method_route_key')
    )
    op.create_index(op.f('ix_idempotency_records_actor_id'), 'idempotency_records', ['actor_id'], unique=False)
    op.create_index(op.f('ix_idempotency_records_expires_at'), 'idempotency_records', ['expires_at'], unique=False)
    op.create_table('llm_invocations',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('logical_step', sa.String(length=50), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'ADMITTED', 'SUCCEEDED', 'FAILED', 'OUTCOME_UNKNOWN', name='llm_invocation_status'), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_resolved', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('request_blob_key', sa.String(length=255), nullable=True),
    sa.Column('response_blob_key', sa.String(length=255), nullable=True),
    sa.Column('provider_request_id', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_reserved', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_actual', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('rate_card_version', sa.String(length=50), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'logical_step', 'attempt_no', name='uq_llm_invocation_step_attempt')
    )
    op.create_index(op.f('ix_llm_invocations_job_id'), 'llm_invocations', ['job_id'], unique=False)
    op.create_table('onboarding_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('walkthrough_version', sa.String(length=50), nullable=False),
    sa.Column('completed_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sandbox_exercise_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'walkthrough_version')
    )
    op.create_table('requisitions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'PAUSED', 'CLOSED', name='requisition_status'), nullable=False),
    sa.Column('current_jd_version_id', sa.UUID(), nullable=True),
    sa.Column('current_rubric_version_id', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitions_organization_id'), 'requisitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_requisitions_status'), 'requisitions', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('csrf_hash', sa.LargeBinary(), nullable=False),
    sa.Column('user_session_generation', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_account_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'RECRUITER', 'REVIEWER', name='account_role'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.create_table('applications',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generation', sa.BigInteger(), nullable=False),
    sa.Column('current_document_id', sa.UUID(), nullable=True),
    sa.Column('current_sanitized_version_id', sa.UUID(), nullable=True),
    sa.Column('current_assessment_run_id', sa.UUID(), nullable=True),
    sa.Column('current_decision_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'candidate_id', name='uq_application_requisition_candidate')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index('ix_applications_req_received', 'applications', ['requisition_id', 'received_at', 'id'], unique=False)
    op.create_index(op.f('ix_applications_requisition_id'), 'applications', ['requisition_id'], unique=False)
    op.create_table('candidate_identities',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('provided_by', sa.String(length=100), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('jd_versions',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('egress_reviewed_by', sa.UUID(), nullable=True),
    sa.Column('egress_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['egress_reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'version_no', name='uq_jd_version_requisition_no')
    )
    op.create_index(op.f('ix_jd_versions_requisition_id'), 'jd_versions', ['requisition_id'], unique=False)
    op.create_table('requisition_memberships',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('membership_role', sa.Enum('OWNER', 'REVIEWER', name='membership_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requisition_id', 'user_id')
    )
    op.create_table('documents',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('original_name_private', sa.String(length=255), nullable=False),
    sa.Column('mime_verified', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('blob_key', sa.String(length=255), nullable=False),
    sa.Column('ingestion_status', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('rendered_pdf_blob_key', sa.String(length=255), nullable=True),
    sa.Column('safety_status', sa.Enum('PENDING', 'PASSED', 'REJECTED', name='document_safety_status'), nullable=False),
    sa.Column('parser_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text_blob_key', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'version_no', name='uq_document_application_version')
    )
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('raw_access_grants',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('grantee_user_id', sa.UUID(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_access_grants_application_id'), 'raw_access_grants', ['application_id'], unique=False)
    op.create_index(op.f('ix_raw_access_grants_expires_at'), 'raw_access_grants', ['expires_at'], unique=False)
    op.create_index(op.f('ix_raw_access_grants_grantee_user_id'), 'raw_access_grants', ['grantee_user_id'], unique=False)
    op.create_table('rubric_versions',
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('jd_version_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', name='rubric_status'), nullable=False),
    sa.Column('threshold_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['jd_version_id'], ['jd_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'version_no', name='uq_rubric_version_requisition_no')
    )
    op.create_index(op.f('ix_rubric_versions_jd_version_id'), 'rubric_versions', ['jd_version_id'], unique=False)
    op.create_index(op.f('ix_rubric_versions_requisition_id'), 'rubric_versions', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_rubric_versions_status'), 'rubric_versions', ['status'], unique=False)
    op.create_table('interview_question_banks',
    sa.Column('rubric_version_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('questions_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_version_id', 'version_no', name='uq_interview_bank_rubric_version')
    )
    op.create_index(op.f('ix_interview_question_banks_rubric_version_id'), 'interview_question_banks', ['rubric_version_id'], unique=False)
    op.create_table('rubric_criteria',
    sa.Column('rubric_version_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.String(length=50), nullable=False),
    sa.Column('label_vi', sa.String(length=200), nullable=False),
    sa.Column('description_vi', sa.Text(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=False),
    sa.Column('anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jd_evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bilingual_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rubric_version_id', 'criterion_id')
    )
    op.create_table('sanitized_versions',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'SUPERSEDED', 'REVOKED', name='sanitized_version_status'), nullable=False),
    sa.Column('canonical_text', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('normalizer_version', sa.String(length=50), nullable=False),
    sa.Column('sanitizer_version', sa.String(length=50), nullable=False),
    sa.Column('renderer_version', sa.String(length=50), nullable=False),
    sa.Column('mapping_blob_key', sa.String(length=255), nullable=True),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_no', name='uq_sanitized_document_version')
    )
    op.create_index(op.f('ix_sanitized_versions_application_id'), 'sanitized_versions', ['application_id'], unique=False)
    op.create_index(op.f('ix_sanitized_versions_document_id'), 'sanitized_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_sanitized_versions_status'), 'sanitized_versions', ['status'], unique=False)
    op.create_table('assessment_runs',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('run_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('application_generation', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('sanitized_version_id', sa.UUID(), nullable=False),
    sa.Column('rubric_version_id', sa.UUID(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('output_schema_version', sa.String(length=50), nullable=False),
    sa.Column('observed_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comparable_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommendation', sa.Enum('CONSIDER_NEXT_ROUND', 'NEEDS_CLARIFICATION', 'REVIEW_REQUIRED', name='recommendation_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('result_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sanitized_version_id'], ['sanitized_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'run_no', name='uq_assessment_run_app_no')
    )
    op.create_index(op.f('ix_assessment_runs_application_id'), 'assessment_runs', ['application_id'], unique=False)
    op.create_index(op.f('ix_assessment_runs_job_id'), 'assessment_runs', ['job_id'], unique=True)
    op.create_index(op.f('ix_assessment_runs_status'), 'assessment_runs', ['status'], unique=False)
    op.create_table('interview_drafts',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('question_bank_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('questions_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_revision_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_bank_id'], ['interview_question_banks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_drafts_application_id'), 'interview_drafts', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_drafts_job_id'), 'interview_drafts', ['job_id'], unique=True)
    op.create_table('retrieval_chunks',
    sa.Column('sanitized_version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('span_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_config_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sanitized_version_id'], ['sanitized_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sanitized_version_id', 'chunk_index', 'embedding_config_id', name='uq_chunk_version_idx_config')
    )
    op.create_index(op.f('ix_retrieval_chunks_sanitized_version_id'), 'retrieval_chunks', ['sanitized_version_id'], unique=False)
    op.create_table('source_spans',
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('full_hash', sa.String(length=64), nullable=False),
    sa.Column('sanitized_version_id', sa.UUID(), nullable=False),
    sa.Column('start_cp', sa.Integer(), nullable=False),
    sa.Column('end_cp', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_label', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sanitized_version_id'], ['sanitized_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('span_id'),
    sa.UniqueConstraint('sanitized_version_id', 'start_cp', 'end_cp', name='uq_source_span_coords')
    )
    op.create_index(op.f('ix_source_spans_sanitized_version_id'), 'source_spans', ['sanitized_version_id'], unique=False)
    op.create_table('criterion_assessments',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ASSESSED', 'INSUFFICIENT_EVIDENCE', 'CONFLICTING_EVIDENCE', name='criterion_outcome'), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'criterion_id')
    )
    op.create_table('criterion_evidence',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.String(length=50), nullable=False),
    sa.Column('span_id', sa.String(length=32), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('resolved_start_cp', sa.Integer(), nullable=False),
    sa.Column('resolved_end_cp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['span_id'], ['source_spans.span_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'criterion_id', 'span_id')
    )
    op.create_table('hr_revisions',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('base_run_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('sanitized_version_id', sa.UUID(), nullable=False),
    sa.Column('rubric_version_id', sa.UUID(), nullable=False),
    sa.Column('application_generation', sa.BigInteger(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criteria_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposed_decision', sa.String(length=50), nullable=True),
    sa.Column('summary_reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('finalized_by', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('observed_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comparable_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['base_run_id'], ['assessment_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sanitized_version_id'], ['sanitized_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'revision_no', name='uq_hr_revision_app_no')
    )
    op.create_index(op.f('ix_hr_revisions_application_id'), 'hr_revisions', ['application_id'], unique=False)
    op.create_table('interview_revisions',
    sa.Column('interview_draft_id', sa.UUID(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('followups_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interview_draft_id'], ['interview_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interview_draft_id', 'revision_no', name='uq_interview_revision_draft_no')
    )
    op.create_index(op.f('ix_interview_revisions_interview_draft_id'), 'interview_revisions', ['interview_draft_id'], unique=False)
    op.create_table('review_attestations',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('decision_basis', sa.Enum('ASSESSMENT_REVIEW', 'MANUAL_DOCUMENT_REVIEW', 'TECHNICAL_INFORMATION_REQUEST', name='decision_basis'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('hr_revision_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('rubric_version_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('application_generation', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_criterion_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual_evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_view_event_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hr_revision_id'], ['hr_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_attestations_application_id'), 'review_attestations', ['application_id'], unique=False)
    op.create_table('decisions',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('decision_basis', sa.Enum('ASSESSMENT_REVIEW', 'MANUAL_DOCUMENT_REVIEW', 'TECHNICAL_INFORMATION_REQUEST', name='decision_basis'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rubric_version_id', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.Enum('ADVANCE', 'REQUEST_INFORMATION', 'NOT_ADVANCE', name='decision_outcome'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('attestation_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('hr_revision_id', sa.UUID(), nullable=True),
    sa.Column('source_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=False),
    sa.Column('supersedes_decision_id', sa.UUID(), nullable=True),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['attestation_id'], ['review_attestations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hr_revision_id'], ['hr_revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['assessment_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_decision_id'], ['decisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'sequence_no', name='uq_decision_app_sequence_no')
    )
    op.create_index(op.f('ix_decisions_application_id'), 'decisions', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_application_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_review_attestations_application_id'), table_name='review_attestations')
    op.drop_table('review_attestations')
    op.drop_index(op.f('ix_interview_revisions_interview_draft_id'), table_name='interview_revisions')
    op.drop_table('interview_revisions')
    op.drop_index(op.f('ix_hr_revisions_application_id'), table_name='hr_revisions')
    op.drop_table('hr_revisions')
    op.drop_table('criterion_evidence')
    op.drop_table('criterion_assessments')
    op.drop_index(op.f('ix_source_spans_sanitized_version_id'), table_name='source_spans')
    op.drop_table('source_spans')
    op.drop_index(op.f('ix_retrieval_chunks_sanitized_version_id'), table_name='retrieval_chunks')
    op.drop_table('retrieval_chunks')
    op.drop_index(op.f('ix_interview_drafts_job_id'), table_name='interview_drafts')
    op.drop_index(op.f('ix_interview_drafts_application_id'), table_name='interview_drafts')
    op.drop_table('interview_drafts')
    op.drop_index(op.f('ix_assessment_runs_status'), table_name='assessment_runs')
    op.drop_index(op.f('ix_assessment_runs_job_id'), table_name='assessment_runs')
    op.drop_index(op.f('ix_assessment_runs_application_id'), table_name='assessment_runs')
    op.drop_table('assessment_runs')
    op.drop_index(op.f('ix_sanitized_versions_status'), table_name='sanitized_versions')
    op.drop_index(op.f('ix_sanitized_versions_document_id'), table_name='sanitized_versions')
    op.drop_index(op.f('ix_sanitized_versions_application_id'), table_name='sanitized_versions')
    op.drop_table('sanitized_versions')
    op.drop_table('rubric_criteria')
    op.drop_index(op.f('ix_interview_question_banks_rubric_version_id'), table_name='interview_question_banks')
    op.drop_table('interview_question_banks')
    op.drop_index(op.f('ix_rubric_versions_status'), table_name='rubric_versions')
    op.drop_index(op.f('ix_rubric_versions_requisition_id'), table_name='rubric_versions')
    op.drop_index(op.f('ix_rubric_versions_jd_version_id'), table_name='rubric_versions')
    op.drop_table('rubric_versions')
    op.drop_index(op.f('ix_raw_access_grants_grantee_user_id'), table_name='raw_access_grants')
    op.drop_index(op.f('ix_raw_access_grants_expires_at'), table_name='raw_access_grants')
    op.drop_index(op.f('ix_raw_access_grants_application_id'), table_name='raw_access_grants')
    op.drop_table('raw_access_grants')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('requisition_memberships')
    op.drop_index(op.f('ix_jd_versions_requisition_id'), table_name='jd_versions')
    op.drop_table('jd_versions')
    op.drop_table('candidate_identities')
    op.drop_index(op.f('ix_applications_requisition_id'), table_name='applications')
    op.drop_index('ix_applications_req_received', table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('user_account_roles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_requisitions_status'), table_name='requisitions')
    op.drop_index(op.f('ix_requisitions_organization_id'), table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_table('onboarding_progress')
    op.drop_index(op.f('ix_llm_invocations_job_id'), table_name='llm_invocations')
    op.drop_table('llm_invocations')
    op.drop_index(op.f('ix_idempotency_records_expires_at'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_actor_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_deletion_requests_target_id'), table_name='deletion_requests')
    op.drop_index(op.f('ix_deletion_requests_status'), table_name='deletion_requests')
    op.drop_table('deletion_requests')
    op.drop_index(op.f('ix_candidates_public_label'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_organization_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_budget_reservations_job_id'), table_name='budget_reservations')
    op.drop_index(op.f('ix_budget_reservations_budget_period_id'), table_name='budget_reservations')
    op.drop_table('budget_reservations')
    op.drop_index(op.f('ix_users_login_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_jobs_target_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('budget_periods')
    op.drop_index('ix_audit_events_occurred_action', table_name='audit_events')
    op.drop_index('ix_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
